name: add_file
on:
  workflow_dispatch:
    inputs:
      id:
        description: 'id of file to edit'
        required: true
      filedata:
        description: 'new data in file'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: delete_old
        run: python devops/delete.py ${{ github.event.inputs.id }}
        shell: sh

      - name: add_new
        run: python devops/add.py ${{ github.event.inputs.id }} ${{ github.event.inputs.data }}
        shell: sh



